# https://www.codechef.com/problems/QUADROOT
# https://www.codechef.com/problems/TEMPLELA
# https://www.codechef.com/problems/PALIN
# https://www.codechef.com/problems/WDTBAM
# https://www.codechef.com/problems/CHEFNWRK
# https://www.codechef.com/problems/CHFGCD
# https://www.codechef.com/problems/CHFPLN
# https://www.codechef.com/problems/MODEQUAL
# https://www.codechef.com/problems/ARRT
# https://www.codechef.com/problems/ETUP
# https://www.codechef.com/problems/MULTHREE
# https://www.codechef.com/problems/XXOORR
# https://www.codechef.com/problems/MINNOTES
# https://www.codechef.com/problems/THREEPTS